version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.9.3

    working_directory: ~/carve-automate

    steps:
      - checkout
      # install carve from binary
      - run:
          wget -O carve.zip https://github.com/borkdude/carve/releases/download/v0.0.1/carve-0.0.1-linux-amd64.zip && unzip carve.zip && chmod +x carve && sudo mv carve /usr/local/bin/

      # check for dead code
      - run: carve
